clear
echo "Test of the standard deviation block"
echo ""
echo ""
echo "Make a post block"
curl "localhost:7070/create?blockType=postto"
echo ""
echo ""
echo "Make an st dev block"
curl "localhost:7070/create?blockType=sd"
echo ""
echo ""
echo "Set a rule for the sd block"
curl "localhost:7070/blocks/2/set_rule" --data '{"Key":"test"}'
echo ""
echo ""
echo "Connect the postto and sd blocks"
curl "localhost:7070/connect?from=1&to=2"
echo ""
echo ""
echo "Send data to the sd block"
curl "localhost:7070/blocks/1/in" --data '{"test":1.0}'
echo ""
echo ""
echo "Get the state of the sd block"
curl "localhost:7070/blocks/2/sd"
echo ""
echo ""
echo "Send data to the sd block"
curl "localhost:7070/blocks/1/in" --data '{"test":2.0}'
echo ""
echo ""
echo "Get sd block state again"
curl "localhost:7070/blocks/2/sd"
echo ""
echo ""
