curl "localhost:7070/create?blockType=random&id=rnd"
curl "localhost:7070/create?blockType=mask&id=mask"
curl "localhost:7070/blocks/mask/set_rule" --data '{"Mask":{"t":{},"random_integers":{}}}'
curl "localhost:7070/connect?from=rnd&to=mask&id=rnd_to_mask"
curl "localhost:7070/create?blockType=sync&id=sync"
curl "localhost:7070/blocks/sync/set_rule" --data '{"Path":"t","Lag":20}'
curl "localhost:7070/connect?from=mask&to=sync&id=mask_to_sync"
curl "localhost:7070/create?blockType=tolog&id=log"
curl "localhost:7070/connect?from=sync&to=log&id=sync_to_log"
echo ""
echo ""
echo "items should start logging in ~20 seconds."
echo "press key to end"
read
echo ""
echo ""
curl "localhost:7070/delete?id=rnd"
curl "localhost:7070/delete?id=mask"
curl "localhost:7070/delete?id=sync"
curl "localhost:7070/delete?id=log"
echo ""
echo ""
curl "localhost:7070"
echo ""
echo ""
echo "done."